name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker image
      run: |
         echo "${{ secrets.DOCKERPW }}" | docker login -u "arnoldroshan" --password-stdin
         docker build -t arnoldroshan/node .
         docker push arnoldroshan/node:latest
